//: "The contents of this file are subject to the Mozilla Public License
//: Version 1.1 (the "License"); you may not use this file except in
//: compliance with the License. You may obtain a copy of the License at
//: http://www.mozilla.org/MPL/
//:
//: Software distributed under the License is distributed on an "AS IS"
//: basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
//: License for the specific language governing rights and limitations
//: under the License.
//:
//: The Original Code is Guanxi (http://www.guanxi.uhi.ac.uk).
//:
//: The Initial Developer of the Original Code is Alistair Young alistair@codebrane.com
//: All Rights Reserved.
//:

package org.guanxi.common.trust.impl;

import org.guanxi.common.trust.TrustEngine;
import org.guanxi.common.trust.PKIXPathValidator;
import org.guanxi.common.metadata.Metadata;

import javax.security.cert.X509Certificate;
import java.util.Vector;

/**
 * TrustEngine implementation that implements the rules of a Shibboleth federation such
 * as the UK Access Management Federation.
 *
 * @author alistair
 */
public class ShibbolethTrustEngineImpl implements TrustEngine, PKIXPathValidator {
  private Vector<X509Certificate> caCerts = null;

  public ShibbolethTrustEngineImpl() {
    caCerts = new Vector<X509Certificate>();
  }

  /**
   * We can hit a problem with certs when the IdP's providerId is, e.g. urn:uni:ac:uk:idp
   * but it's cert DN is CN=urn:uni:ac:uk:idp, OU=Unknown, O=Unknown, L=Unknown, ST=Unknown, C=Unknown
   * We didn't see this in the beginning as the certs generated by BouncyCastle in the IdP don't have
   * the extra OU etc. Most commandline tools do put the extra OU in if you don't specify them.
   *
   * Also, just about anything can be in the subject so the safest method is to find the cert in the
   * SAML Reponse and match it against one that's in the certificate store.
   *
   * @see org.guanxi.common.trust.PKIXPathValidator#addCert(javax.security.cert.X509Certificate) */
  public void addCert(X509Certificate x509Cert) {
    caCerts.add(x509Cert);
  }

  /** @see org.guanxi.common.trust.TrustEngine#trustEntity(org.guanxi.common.metadata.Metadata, Object) */
  public boolean trustEntity(Metadata entityMetadata, Object entityData) {
    //@todo default implementation - change
    return true;
  }

  /** @see org.guanxi.common.trust.PKIXPathValidator#reset() */
  public void reset() {
    caCerts.clear();
  }
}
